imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apcu
        query_cache_driver: apcu

monolog:
    handlers:
        main:
            type: fingers_crossed
            channels: ['!app_access']
            action_level: error
            handler: nested
            excluded_404s:
                - ^/
        app_access:
            type:  stream
            channels: ['app_access']
            path:  "%kernel.logs_dir%/%kernel.environment%-access.log"
            level: info
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
framework:
    cache:
        default_redis_provider: "redis://%redis_host%"
        pools:
            cache.programmes:
                public: true
                adapter: cache.adapter.redis
                default_lifetime: 120
